### ISSUE TITLE
Email doesn't work

### ISSUE THREAD

**Issue by BenjaminPelletier** [RopeWiki/app#6]
When attempting to email user (site feature), the error message "Unknown error in PHP's mail() function."  This probably means the site is unable to send any kind of email.

**Comment by casconed** [comment]
I would definitely recommend a service like Mailgun for this - their flex plan includes 5000 emails per month for 3 months, then $0.80 / 1000 emails thereafter. Depending on your transaction volume it is pretty economical. 

If that is not in the cards I'd be happy to take a stab at the Docker implementation

**Comment by BenjaminPelletier** [comment]
#34 is now deployed on the production site and email seems to be working.
